# Generated by Django 4.0.4 on 2022-05-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('overview', models.TextField()),
                ('body', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('posted', models.DateField(auto_now_add=True, db_index=True)),
                ('featured', models.BooleanField()),
                ('categories', models.ManyToManyField(to='blogposts.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
