# Generated by Django 4.0.4 on 2022-05-26 08:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0003_post_comment_count_post_view_count_alter_post_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
