# Generated by Django 4.0.4 on 2022-05-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='overview',
            field=models.TextField(default='Category info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(default='photo', upload_to=''),
            preserve_default=False,
        ),
    ]
