# Generated by Django 4.0.4 on 2022-05-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0008_remove_post_comment_count_remove_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postview',
            name='user_ip',
            field=models.GenericIPAddressField(),
        ),
    ]
